# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  twitter_api_key: x6VTZfo3rJPUUVwJr9Sp7Wc
  twitter_api_secret: Uj4b8SZ4Zvze9s2tmsYOvODavYUpjU3alQIZaokwZia4MOGvSX
  secret_key_base: 277b75790e9b2f9f46f6a320a8215b184aaa5051c176e460f79fd45a4f4aea49e2207a0fb3c68f11324f5b3d167eb096ffcd931abd5e63639083330dbbb44bee

test:
  secret_key_base: 2f3857ded1567363caa0b649b5635c0aa7d9c2f141465a4681ea0b3c3ca6d9868e11da244a4351771570998d7b34a0553aad1e253c5c7aead37d8354898e083e

production:
  twitter_api_key: x6VTZfo3rJPUUVwJr9Sp7Wc
  twitter_api_secret: Uj4b8SZ4Zvze9s2tmsYOvODavYUpjU3alQIZaokwZia4MOGvSX

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
